"""README generation with manual download instructions."""

from __future__ import annotations

from pathlib import Path

from .datasets import DATASETS, DatasetConfig


def generate_instructions(config: DatasetConfig, data_dir: Path) -> None:
    """Print and record manual instructions for a dataset."""
    print(f"\n--- {config.display_name} ---")
    print(config.manual_instructions)
    print()


def generate_readme(data_dir: Path, state: dict) -> None:
    """Generate ~/data/conducting/README.md with dataset status and instructions."""
    lines = [
        "# Conducting Datasets",
        "",
        "Auto-generated by `python -m src.data.download_datasets`.",
        "",
        "## Dataset Status",
        "",
    ]

    for name, cfg in DATASETS.items():
        s = state.get(name, {})
        status = s.get("status", "not started")
        lines.append(f"### {cfg.display_name}")
        lines.append(f"- **Status:** {status}")
        lines.append(f"- **Directory:** `{cfg.target_dir}/`")
        lines.append(f"- **Description:** {cfg.description}")
        if cfg.manual_instructions:
            lines.append(f"\n**Instructions:**\n{cfg.manual_instructions}")
        lines.append("")

    readme = data_dir / "README.md"
    readme.write_text("\n".join(lines) + "\n")
    print(f"README written to {readme}")
